BUFFER = 1024
DATABASE_FILE_PATH = "./src/database/dbs"
MENU_SIZE = 50
POST_LIFETIME = 20 # seconds
GARBAGE_COLLECTOR_FREQUENCY = 10 # seconds
NTP_MAX_TRIES = 3

MIN_USERNAME_SIZE = 2
MAX_USERNAME_SIZE = 40 # characters
MAX_POST_SIZE = 280 # characters 